<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerQonzHRa\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQonzHRa/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQonzHRa.legacy');
=======
if (\class_exists(\ContainerWEbJfBh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEbJfBh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWEbJfBh.legacy');
>>>>>>> cf867d55532c59449e71f3f52f644e4883f45836

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerQonzHRa\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQonzHRa\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'QonzHRa',
    'container.build_id' => '3b39b110',
    'container.build_time' => 1541593114,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQonzHRa');
=======
    \class_alias(\ContainerWEbJfBh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWEbJfBh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WEbJfBh',
    'container.build_id' => '1c085345',
    'container.build_time' => 1541587973,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEbJfBh');
>>>>>>> cf867d55532c59449e71f3f52f644e4883f45836
