<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWEbJfBh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWEbJfBh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWEbJfBh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWEbJfBh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWEbJfBh\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WEbJfBh',
    'container.build_id' => '1c085345',
    'container.build_time' => 1541587973,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWEbJfBh');
