<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIY9kkax\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIY9kkax/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIY9kkax.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIY9kkax\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIY9kkax\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IY9kkax',
    'container.build_id' => '692106fd',
    'container.build_time' => 1541516867,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIY9kkax');
